// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace BR.ToteToToe.Web.Controllers
{
    public partial class CustomizeController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CustomizeController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected CustomizeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ShoeColour()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShoeColour);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ShoeDetails()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShoeDetails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult FilterHeelHeight()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.FilterHeelHeight);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CustomizeController Actions { get { return MVC.Customize; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Customize";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Customize";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string ShoeStyle = "ShoeStyle";
            public readonly string ShoeColour = "ShoeColour";
            public readonly string ShoeDetails = "ShoeDetails";
            public readonly string FilterHeelHeight = "FilterHeelHeight";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string ShoeStyle = "ShoeStyle";
            public const string ShoeColour = "ShoeColour";
            public const string ShoeDetails = "ShoeDetails";
            public const string FilterHeelHeight = "FilterHeelHeight";
        }


        static readonly ActionParamsClass_ShoeColour s_params_ShoeColour = new ActionParamsClass_ShoeColour();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ShoeColour ShoeColourParams { get { return s_params_ShoeColour; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ShoeColour
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ShoeDetails s_params_ShoeDetails = new ActionParamsClass_ShoeDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ShoeDetails ShoeDetailsParams { get { return s_params_ShoeDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ShoeDetails
        {
            public readonly string sku = "sku";
            public readonly string viewModel = "viewModel";
            public readonly string collection = "collection";
        }
        static readonly ActionParamsClass_FilterHeelHeight s_params_FilterHeelHeight = new ActionParamsClass_FilterHeelHeight();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_FilterHeelHeight FilterHeelHeightParams { get { return s_params_FilterHeelHeight; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_FilterHeelHeight
        {
            public readonly string id = "id";
            public readonly string heelHeight = "heelHeight";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _ShoeColour = "_ShoeColour";
                public readonly string _SizeChart = "_SizeChart";
                public readonly string ShoeColour = "ShoeColour";
                public readonly string ShoeDetails = "ShoeDetails";
                public readonly string ShoeDetais = "ShoeDetais";
                public readonly string ShoeStyle = "ShoeStyle";
            }
            public readonly string _ShoeColour = "~/Views/Customize/_ShoeColour.cshtml";
            public readonly string _SizeChart = "~/Views/Customize/_SizeChart.cshtml";
            public readonly string ShoeColour = "~/Views/Customize/ShoeColour.cshtml";
            public readonly string ShoeDetails = "~/Views/Customize/ShoeDetails.cshtml";
            public readonly string ShoeDetais = "~/Views/Customize/ShoeDetais.cshtml";
            public readonly string ShoeStyle = "~/Views/Customize/ShoeStyle.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_CustomizeController : BR.ToteToToe.Web.Controllers.CustomizeController
    {
        public T4MVC_CustomizeController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void ShoeStyleOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult ShoeStyle()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShoeStyle);
            ShoeStyleOverride(callInfo);
            return callInfo;
        }

        partial void ShoeColourOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult ShoeColour(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShoeColour);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ShoeColourOverride(callInfo, id);
            return callInfo;
        }

        partial void ShoeDetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string sku);

        public override System.Web.Mvc.ActionResult ShoeDetails(string sku)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShoeDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sku", sku);
            ShoeDetailsOverride(callInfo, sku);
            return callInfo;
        }

        partial void ShoeDetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, BR.ToteToToe.Web.ViewModels.ShoeDetailsViewModel viewModel, System.Web.Mvc.FormCollection collection);

        public override System.Web.Mvc.ActionResult ShoeDetails(BR.ToteToToe.Web.ViewModels.ShoeDetailsViewModel viewModel, System.Web.Mvc.FormCollection collection)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShoeDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "collection", collection);
            ShoeDetailsOverride(callInfo, viewModel, collection);
            return callInfo;
        }

        partial void FilterHeelHeightOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int id, int heelHeight);

        public override System.Web.Mvc.JsonResult FilterHeelHeight(int id, int heelHeight)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.FilterHeelHeight);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "heelHeight", heelHeight);
            FilterHeelHeightOverride(callInfo, id, heelHeight);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
