// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace BR.ToteToToe.Web.Controllers
{
    public partial class ShoesController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ShoesController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ShoesController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Details()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult Filter()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Filter);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetModelSizeByModel()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetModelSizeByModel);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetQtyByModelSize()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetQtyByModelSize);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetModelImagesByColour()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetModelImagesByColour);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ShoesController Actions { get { return MVC.Shoes; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Shoes";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Shoes";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string List = "List";
            public readonly string Pumps = "Pumps";
            public readonly string Details = "Details";
            public readonly string Filter = "Filter";
            public readonly string GetModelSizeByModel = "GetModelSizeByModel";
            public readonly string GetQtyByModelSize = "GetQtyByModelSize";
            public readonly string GetModelImagesByColour = "GetModelImagesByColour";
            public readonly string _SizeChart = "_SizeChart";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string List = "List";
            public const string Pumps = "Pumps";
            public const string Details = "Details";
            public const string Filter = "Filter";
            public const string GetModelSizeByModel = "GetModelSizeByModel";
            public const string GetQtyByModelSize = "GetQtyByModelSize";
            public const string GetModelImagesByColour = "GetModelImagesByColour";
            public const string _SizeChart = "_SizeChart";
        }


        static readonly ActionParamsClass_List s_params_List = new ActionParamsClass_List();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_List ListParams { get { return s_params_List; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_List
        {
            public readonly string categoryID = "categoryID";
        }
        static readonly ActionParamsClass_Details s_params_Details = new ActionParamsClass_Details();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Details DetailsParams { get { return s_params_Details; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Details
        {
            public readonly string modelID = "modelID";
            public readonly string colourDescID = "colourDescID";
            public readonly string modelSizeID = "modelSizeID";
            public readonly string viewModel = "viewModel";
            public readonly string collection = "collection";
        }
        static readonly ActionParamsClass_Filter s_params_Filter = new ActionParamsClass_Filter();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Filter FilterParams { get { return s_params_Filter; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Filter
        {
            public readonly string categoryID = "categoryID";
            public readonly string trendID = "trendID";
            public readonly string lifestyleID = "lifestyleID";
            public readonly string brandName = "brandName";
            public readonly string size = "size";
            public readonly string colourID = "colourID";
            public readonly string price = "price";
            public readonly string heelHeight = "heelHeight";
        }
        static readonly ActionParamsClass_GetModelSizeByModel s_params_GetModelSizeByModel = new ActionParamsClass_GetModelSizeByModel();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetModelSizeByModel GetModelSizeByModelParams { get { return s_params_GetModelSizeByModel; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetModelSizeByModel
        {
            public readonly string modelID = "modelID";
            public readonly string colourDescID = "colourDescID";
            public readonly string modelSizeID = "modelSizeID";
        }
        static readonly ActionParamsClass_GetQtyByModelSize s_params_GetQtyByModelSize = new ActionParamsClass_GetQtyByModelSize();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetQtyByModelSize GetQtyByModelSizeParams { get { return s_params_GetQtyByModelSize; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetQtyByModelSize
        {
            public readonly string modelSizeID = "modelSizeID";
        }
        static readonly ActionParamsClass_GetModelImagesByColour s_params_GetModelImagesByColour = new ActionParamsClass_GetModelImagesByColour();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetModelImagesByColour GetModelImagesByColourParams { get { return s_params_GetModelImagesByColour; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetModelImagesByColour
        {
            public readonly string modelID = "modelID";
            public readonly string colourDescID = "colourDescID";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _DetailsImages = "_DetailsImages";
                public readonly string _ListItem = "_ListItem";
                public readonly string _ListItemParent = "_ListItemParent";
                public readonly string _ListItems = "_ListItems";
                public readonly string _ModelSizeDDL = "_ModelSizeDDL";
                public readonly string _SizeChart = "_SizeChart";
                public readonly string Details = "Details";
                public readonly string Index = "Index";
                public readonly string List = "List";
                public readonly string Pumps = "Pumps";
            }
            public readonly string _DetailsImages = "~/Views/Shoes/_DetailsImages.cshtml";
            public readonly string _ListItem = "~/Views/Shoes/_ListItem.cshtml";
            public readonly string _ListItemParent = "~/Views/Shoes/_ListItemParent.cshtml";
            public readonly string _ListItems = "~/Views/Shoes/_ListItems.cshtml";
            public readonly string _ModelSizeDDL = "~/Views/Shoes/_ModelSizeDDL.cshtml";
            public readonly string _SizeChart = "~/Views/Shoes/_SizeChart.cshtml";
            public readonly string Details = "~/Views/Shoes/Details.cshtml";
            public readonly string Index = "~/Views/Shoes/Index.cshtml";
            public readonly string List = "~/Views/Shoes/List.cshtml";
            public readonly string Pumps = "~/Views/Shoes/Pumps.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ShoesController : BR.ToteToToe.Web.Controllers.ShoesController
    {
        public T4MVC_ShoesController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void ListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int categoryID);

        public override System.Web.Mvc.ActionResult List(int categoryID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.List);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "categoryID", categoryID);
            ListOverride(callInfo, categoryID);
            return callInfo;
        }

        partial void PumpsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Pumps()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Pumps);
            PumpsOverride(callInfo);
            return callInfo;
        }

        partial void DetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int modelID, int colourDescID, int modelSizeID);

        public override System.Web.Mvc.ActionResult Details(int modelID, int colourDescID, int modelSizeID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "modelID", modelID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "colourDescID", colourDescID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "modelSizeID", modelSizeID);
            DetailsOverride(callInfo, modelID, colourDescID, modelSizeID);
            return callInfo;
        }

        partial void DetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, BR.ToteToToe.Web.ViewModels.ModelDetailsViewModel viewModel, System.Web.Mvc.FormCollection collection);

        public override System.Web.Mvc.ActionResult Details(BR.ToteToToe.Web.ViewModels.ModelDetailsViewModel viewModel, System.Web.Mvc.FormCollection collection)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "collection", collection);
            DetailsOverride(callInfo, viewModel, collection);
            return callInfo;
        }

        partial void FilterOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int categoryID, int trendID, int lifestyleID, string brandName, string size, int colourID, string price, int heelHeight);

        public override System.Web.Mvc.JsonResult Filter(int categoryID, int trendID, int lifestyleID, string brandName, string size, int colourID, string price, int heelHeight)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Filter);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "categoryID", categoryID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "trendID", trendID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lifestyleID", lifestyleID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "brandName", brandName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "size", size);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "colourID", colourID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "price", price);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "heelHeight", heelHeight);
            FilterOverride(callInfo, categoryID, trendID, lifestyleID, brandName, size, colourID, price, heelHeight);
            return callInfo;
        }

        partial void GetModelSizeByModelOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string modelID, string colourDescID, string modelSizeID);

        public override System.Web.Mvc.JsonResult GetModelSizeByModel(string modelID, string colourDescID, string modelSizeID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetModelSizeByModel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "modelID", modelID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "colourDescID", colourDescID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "modelSizeID", modelSizeID);
            GetModelSizeByModelOverride(callInfo, modelID, colourDescID, modelSizeID);
            return callInfo;
        }

        partial void GetQtyByModelSizeOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string modelSizeID);

        public override System.Web.Mvc.JsonResult GetQtyByModelSize(string modelSizeID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetQtyByModelSize);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "modelSizeID", modelSizeID);
            GetQtyByModelSizeOverride(callInfo, modelSizeID);
            return callInfo;
        }

        partial void GetModelImagesByColourOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string modelID, string colourDescID);

        public override System.Web.Mvc.JsonResult GetModelImagesByColour(string modelID, string colourDescID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetModelImagesByColour);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "modelID", modelID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "colourDescID", colourDescID);
            GetModelImagesByColourOverride(callInfo, modelID, colourDescID);
            return callInfo;
        }

        partial void _SizeChartOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        public override System.Web.Mvc.PartialViewResult _SizeChart()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames._SizeChart);
            _SizeChartOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
