// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace BR.ToteToToe.Web.Controllers
{
    public partial class SignInController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SignInController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SignInController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult FacebookLogin()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FacebookLogin);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult FacebookLoginCallback()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FacebookLoginCallback);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Register()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Register);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult VerifyEmail()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.VerifyEmail);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ConfirmEmail()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ConfirmEmail);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult WelcomeLogin()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.WelcomeLogin);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SignInController Actions { get { return MVC.SignIn; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "SignIn";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "SignIn";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string FacebookLogin = "FacebookLogin";
            public readonly string FacebookLoginCallback = "FacebookLoginCallback";
            public readonly string Register = "Register";
            public readonly string VerifyEmail = "VerifyEmail";
            public readonly string ConfirmEmail = "ConfirmEmail";
            public readonly string WelcomeLogin = "WelcomeLogin";
            public readonly string Logout = "Logout";
            public readonly string FacebookLoginFailure = "FacebookLoginFailure";
            public readonly string ForgotPassword = "ForgotPassword";
            public readonly string ForgotPasswordSuccess = "ForgotPasswordSuccess";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string FacebookLogin = "FacebookLogin";
            public const string FacebookLoginCallback = "FacebookLoginCallback";
            public const string Register = "Register";
            public const string VerifyEmail = "VerifyEmail";
            public const string ConfirmEmail = "ConfirmEmail";
            public const string WelcomeLogin = "WelcomeLogin";
            public const string Logout = "Logout";
            public const string FacebookLoginFailure = "FacebookLoginFailure";
            public const string ForgotPassword = "ForgotPassword";
            public const string ForgotPasswordSuccess = "ForgotPasswordSuccess";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string returnUrl = "returnUrl";
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_FacebookLogin s_params_FacebookLogin = new ActionParamsClass_FacebookLogin();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_FacebookLogin FacebookLoginParams { get { return s_params_FacebookLogin; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_FacebookLogin
        {
            public readonly string provider = "provider";
            public readonly string returnUrl = "returnUrl";
        }
        static readonly ActionParamsClass_FacebookLoginCallback s_params_FacebookLoginCallback = new ActionParamsClass_FacebookLoginCallback();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_FacebookLoginCallback FacebookLoginCallbackParams { get { return s_params_FacebookLoginCallback; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_FacebookLoginCallback
        {
            public readonly string returnUrl = "returnUrl";
        }
        static readonly ActionParamsClass_Register s_params_Register = new ActionParamsClass_Register();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Register RegisterParams { get { return s_params_Register; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Register
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_VerifyEmail s_params_VerifyEmail = new ActionParamsClass_VerifyEmail();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_VerifyEmail VerifyEmailParams { get { return s_params_VerifyEmail; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_VerifyEmail
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ActionParamsClass_ConfirmEmail s_params_ConfirmEmail = new ActionParamsClass_ConfirmEmail();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ConfirmEmail ConfirmEmailParams { get { return s_params_ConfirmEmail; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ConfirmEmail
        {
            public readonly string token = "token";
            public readonly string email = "email";
        }
        static readonly ActionParamsClass_WelcomeLogin s_params_WelcomeLogin = new ActionParamsClass_WelcomeLogin();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_WelcomeLogin WelcomeLoginParams { get { return s_params_WelcomeLogin; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_WelcomeLogin
        {
            public readonly string t = "t";
            public readonly string email = "email";
        }
        static readonly ActionParamsClass_ForgotPassword s_params_ForgotPassword = new ActionParamsClass_ForgotPassword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ForgotPassword ForgotPasswordParams { get { return s_params_ForgotPassword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ForgotPassword
        {
            public readonly string viewModel = "viewModel";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string ConfirmEmail = "ConfirmEmail";
                public readonly string FacebookLoginFailure = "FacebookLoginFailure";
                public readonly string ForgotPassword = "ForgotPassword";
                public readonly string ForgotPasswordSuccess = "ForgotPasswordSuccess";
                public readonly string Index = "Index";
                public readonly string Register = "Register";
                public readonly string ResetPassword = "ResetPassword";
                public readonly string VerifyEmail = "VerifyEmail";
                public readonly string VerifyEmailSent = "VerifyEmailSent";
                public readonly string WelcomeEmail = "WelcomeEmail";
            }
            public readonly string ConfirmEmail = "~/Views/SignIn/ConfirmEmail.cshtml";
            public readonly string FacebookLoginFailure = "~/Views/SignIn/FacebookLoginFailure.cshtml";
            public readonly string ForgotPassword = "~/Views/SignIn/ForgotPassword.cshtml";
            public readonly string ForgotPasswordSuccess = "~/Views/SignIn/ForgotPasswordSuccess.cshtml";
            public readonly string Index = "~/Views/SignIn/Index.cshtml";
            public readonly string Register = "~/Views/SignIn/Register.cshtml";
            public readonly string ResetPassword = "~/Views/SignIn/ResetPassword.cshtml";
            public readonly string VerifyEmail = "~/Views/SignIn/VerifyEmail.cshtml";
            public readonly string VerifyEmailSent = "~/Views/SignIn/VerifyEmailSent.cshtml";
            public readonly string WelcomeEmail = "~/Views/SignIn/WelcomeEmail.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_SignInController : BR.ToteToToe.Web.Controllers.SignInController
    {
        public T4MVC_SignInController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string returnUrl);

        public override System.Web.Mvc.ActionResult Index(string returnUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl);
            IndexOverride(callInfo, returnUrl);
            return callInfo;
        }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, BR.ToteToToe.Web.ViewModels.SignInViewModel viewModel, string returnUrl);

        public override System.Web.Mvc.ActionResult Index(BR.ToteToToe.Web.ViewModels.SignInViewModel viewModel, string returnUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl);
            IndexOverride(callInfo, viewModel, returnUrl);
            return callInfo;
        }

        partial void FacebookLoginOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string provider, string returnUrl);

        public override System.Web.Mvc.ActionResult FacebookLogin(string provider, string returnUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FacebookLogin);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "provider", provider);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl);
            FacebookLoginOverride(callInfo, provider, returnUrl);
            return callInfo;
        }

        partial void FacebookLoginCallbackOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string returnUrl);

        public override System.Web.Mvc.ActionResult FacebookLoginCallback(string returnUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FacebookLoginCallback);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl);
            FacebookLoginCallbackOverride(callInfo, returnUrl);
            return callInfo;
        }

        partial void RegisterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, BR.ToteToToe.Web.ViewModels.SignInViewModel viewModel);

        public override System.Web.Mvc.ActionResult Register(BR.ToteToToe.Web.ViewModels.SignInViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Register);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            RegisterOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void VerifyEmailOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, BR.ToteToToe.Web.ViewModels.VerifyEmailViewModel viewModel);

        public override System.Web.Mvc.ActionResult VerifyEmail(BR.ToteToToe.Web.ViewModels.VerifyEmailViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.VerifyEmail);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            VerifyEmailOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void ConfirmEmailOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string token, string email);

        public override System.Web.Mvc.ActionResult ConfirmEmail(string token, string email)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ConfirmEmail);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "token", token);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "email", email);
            ConfirmEmailOverride(callInfo, token, email);
            return callInfo;
        }

        partial void WelcomeLoginOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string t, string email);

        public override System.Web.Mvc.ActionResult WelcomeLogin(string t, string email)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.WelcomeLogin);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "t", t);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "email", email);
            WelcomeLoginOverride(callInfo, t, email);
            return callInfo;
        }

        partial void LogoutOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Logout()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Logout);
            LogoutOverride(callInfo);
            return callInfo;
        }

        partial void FacebookLoginFailureOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult FacebookLoginFailure()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FacebookLoginFailure);
            FacebookLoginFailureOverride(callInfo);
            return callInfo;
        }

        partial void ForgotPasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult ForgotPassword()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ForgotPassword);
            ForgotPasswordOverride(callInfo);
            return callInfo;
        }

        partial void ForgotPasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, BR.ToteToToe.Web.ViewModels.ForgotPasswordViewModel viewModel);

        public override System.Web.Mvc.ActionResult ForgotPassword(BR.ToteToToe.Web.ViewModels.ForgotPasswordViewModel viewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ForgotPassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewModel", viewModel);
            ForgotPasswordOverride(callInfo, viewModel);
            return callInfo;
        }

        partial void ForgotPasswordSuccessOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult ForgotPasswordSuccess()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ForgotPasswordSuccess);
            ForgotPasswordSuccessOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
