// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static class MVC
{
    static readonly AdminClass s_Admin = new AdminClass();
    public static AdminClass Admin { get { return s_Admin; } }
    public static BR.ToteToToe.Web.Controllers.AccountController Account = new BR.ToteToToe.Web.Controllers.T4MVC_AccountController();
    public static BR.ToteToToe.Web.Controllers.ArticlesController Articles = new BR.ToteToToe.Web.Controllers.T4MVC_ArticlesController();
    public static BR.ToteToToe.Web.Controllers.CheckoutController Checkout = new BR.ToteToToe.Web.Controllers.T4MVC_CheckoutController();
    public static BR.ToteToToe.Web.Controllers.CustomizeController Customize = new BR.ToteToToe.Web.Controllers.T4MVC_CustomizeController();
    public static BR.ToteToToe.Web.Controllers.ErrorController Error = new BR.ToteToToe.Web.Controllers.T4MVC_ErrorController();
    public static BR.ToteToToe.Web.Controllers.HandbagsController Handbags = new BR.ToteToToe.Web.Controllers.T4MVC_HandbagsController();
    public static BR.ToteToToe.Web.Controllers.HomeController Home = new BR.ToteToToe.Web.Controllers.T4MVC_HomeController();
    public static BR.ToteToToe.Web.Controllers.MyAccountController MyAccount = new BR.ToteToToe.Web.Controllers.T4MVC_MyAccountController();
    public static BR.ToteToToe.Web.Controllers.OrderController Order = new BR.ToteToToe.Web.Controllers.T4MVC_OrderController();
    public static BR.ToteToToe.Web.Controllers.PaymentController Payment = new BR.ToteToToe.Web.Controllers.T4MVC_PaymentController();
    public static BR.ToteToToe.Web.Controllers.ShoesController Shoes = new BR.ToteToToe.Web.Controllers.T4MVC_ShoesController();
    public static BR.ToteToToe.Web.Controllers.ShoppingBagController ShoppingBag = new BR.ToteToToe.Web.Controllers.T4MVC_ShoppingBagController();
    public static BR.ToteToToe.Web.Controllers.SignInController SignIn = new BR.ToteToToe.Web.Controllers.T4MVC_SignInController();
    public static BR.ToteToToe.Web.Controllers.TrendingController Trending = new BR.ToteToToe.Web.Controllers.T4MVC_TrendingController();
    public static BR.ToteToToe.Web.Controllers.WishlistController Wishlist = new BR.ToteToToe.Web.Controllers.T4MVC_WishlistController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class AdminClass
    {
        public readonly string Name = "Admin";
        public BR.ToteToToe.Web.Areas.Admin.Controllers.OrderStatusController OrderStatus = new BR.ToteToToe.Web.Areas.Admin.Controllers.T4MVC_OrderStatusController();
        public BR.ToteToToe.Web.Areas.Admin.Controllers.TrendPriorityController TrendPriority = new BR.ToteToToe.Web.Areas.Admin.Controllers.T4MVC_TrendPriorityController();
        public BR.ToteToToe.Web.Areas.Admin.Controllers.VoucherController Voucher = new BR.ToteToToe.Web.Areas.Admin.Controllers.T4MVC_VoucherController();
        public T4MVC.Admin.SharedController Shared = new T4MVC.Admin.SharedController();
    }
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_JsonResult : System.Web.Mvc.JsonResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_JsonResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_PartialViewResult : System.Web.Mvc.PartialViewResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_PartialViewResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        private const string URLPATH = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string _references_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/_references.min.js") ? Url("_references.min.js") : Url("_references.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class _2013_2_611 {
            private const string URLPATH = "~/Scripts/2013.2.611";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string jquery_1_7_1_min_js = Url("jquery-1.7.1.min.js");
            public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
            public static readonly string telerik_all_min_js = Url("telerik.all.min.js");
            public static readonly string telerik_autocomplete_min_js = Url("telerik.autocomplete.min.js");
            public static readonly string telerik_calendar_min_js = Url("telerik.calendar.min.js");
            public static readonly string telerik_chart_min_js = Url("telerik.chart.min.js");
            public static readonly string telerik_combobox_min_js = Url("telerik.combobox.min.js");
            public static readonly string telerik_common_min_js = Url("telerik.common.min.js");
            public static readonly string telerik_datepicker_min_js = Url("telerik.datepicker.min.js");
            public static readonly string telerik_datetimepicker_min_js = Url("telerik.datetimepicker.min.js");
            public static readonly string telerik_draganddrop_min_js = Url("telerik.draganddrop.min.js");
            public static readonly string telerik_editor_min_js = Url("telerik.editor.min.js");
            public static readonly string telerik_grid_editing_min_js = Url("telerik.grid.editing.min.js");
            public static readonly string telerik_grid_filtering_min_js = Url("telerik.grid.filtering.min.js");
            public static readonly string telerik_grid_grouping_min_js = Url("telerik.grid.grouping.min.js");
            public static readonly string telerik_grid_min_js = Url("telerik.grid.min.js");
            public static readonly string telerik_grid_reordering_min_js = Url("telerik.grid.reordering.min.js");
            public static readonly string telerik_grid_resizing_min_js = Url("telerik.grid.resizing.min.js");
            public static readonly string telerik_imagebrowser_min_js = Url("telerik.imagebrowser.min.js");
            public static readonly string telerik_list_min_js = Url("telerik.list.min.js");
            public static readonly string telerik_menu_min_js = Url("telerik.menu.min.js");
            public static readonly string telerik_panelbar_min_js = Url("telerik.panelbar.min.js");
            public static readonly string telerik_slider_min_js = Url("telerik.slider.min.js");
            public static readonly string telerik_splitter_min_js = Url("telerik.splitter.min.js");
            public static readonly string telerik_tabstrip_min_js = Url("telerik.tabstrip.min.js");
            public static readonly string telerik_textbox_min_js = Url("telerik.textbox.min.js");
            public static readonly string telerik_timepicker_min_js = Url("telerik.timepicker.min.js");
            public static readonly string telerik_treeview_min_js = Url("telerik.treeview.min.js");
            public static readonly string telerik_upload_min_js = Url("telerik.upload.min.js");
            public static readonly string telerik_window_min_js = Url("telerik.window.min.js");
        }
    
        public static readonly string bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.js") ? Url("bootstrap.min.js") : Url("bootstrap.js");
        public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
        public static readonly string jquery_1_9_0_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.9.0.intellisense.min.js") ? Url("jquery-1.9.0.intellisense.min.js") : Url("jquery-1.9.0.intellisense.js");
        public static readonly string jquery_1_9_0_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.9.0.min.js") ? Url("jquery-1.9.0.min.js") : Url("jquery-1.9.0.js");
        public static readonly string jquery_1_9_0_min_js = Url("jquery-1.9.0.min.js");
        public static readonly string jquery_1_9_0_min_map = Url("jquery-1.9.0.min.map");
        public static readonly string jquery_ui_1_8_24_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui-1.8.24.min.js") ? Url("jquery-ui-1.8.24.min.js") : Url("jquery-ui-1.8.24.js");
        public static readonly string jquery_ui_1_8_24_min_js = Url("jquery-ui-1.8.24.min.js");
        public static readonly string jquery_unobtrusive_ajax_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.unobtrusive-ajax.min.js") ? Url("jquery.unobtrusive-ajax.min.js") : Url("jquery.unobtrusive-ajax.js");
        public static readonly string jquery_unobtrusive_ajax_min_js = Url("jquery.unobtrusive-ajax.min.js");
        public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
        public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
        public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
        public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
        public static readonly string jquery_validate_unobtrusive_min_js = Url("jquery.validate.unobtrusive.min.js");
        public static readonly string knockout_2_2_0_debug_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/knockout-2.2.0.debug.min.js") ? Url("knockout-2.2.0.debug.min.js") : Url("knockout-2.2.0.debug.js");
        public static readonly string knockout_2_2_0_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/knockout-2.2.0.min.js") ? Url("knockout-2.2.0.min.js") : Url("knockout-2.2.0.js");
        public static readonly string modernizr_2_6_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/modernizr-2.6.2.min.js") ? Url("modernizr-2.6.2.min.js") : Url("modernizr-2.6.2.js");
        public static readonly string mvcfoolproof_unobtrusive_min_js = Url("mvcfoolproof.unobtrusive.min.js");
        public static readonly string MvcFoolproofJQueryValidation_min_js = Url("MvcFoolproofJQueryValidation.min.js");
        public static readonly string MvcFoolproofValidation_min_js = Url("MvcFoolproofValidation.min.js");
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        private const string URLPATH = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class _2013_2_611 {
            private const string URLPATH = "~/Content/2013.2.611";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Black {
                private const string URLPATH = "~/Content/2013.2.611/Black";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string editor_png = Url("editor.png");
                public static readonly string imagebrowser_png = Url("imagebrowser.png");
                public static readonly string loading_gif = Url("loading.gif");
                public static readonly string slider_h_gif = Url("slider-h.gif");
                public static readonly string slider_v_gif = Url("slider-v.gif");
                public static readonly string sprite_vertical_png = Url("sprite-vertical.png");
                public static readonly string sprite_png = Url("sprite.png");
                public static readonly string treeview_line_png = Url("treeview-line.png");
                public static readonly string treeview_nodes_rtl_png = Url("treeview-nodes-rtl.png");
                public static readonly string treeview_nodes_png = Url("treeview-nodes.png");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Default {
                private const string URLPATH = "~/Content/2013.2.611/Default";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string editor_png = Url("editor.png");
                public static readonly string imagebrowser_png = Url("imagebrowser.png");
                public static readonly string loading_gif = Url("loading.gif");
                public static readonly string slider_h_gif = Url("slider-h.gif");
                public static readonly string slider_v_gif = Url("slider-v.gif");
                public static readonly string sprite_vertical_png = Url("sprite-vertical.png");
                public static readonly string sprite_png = Url("sprite.png");
                public static readonly string treeview_line_png = Url("treeview-line.png");
                public static readonly string treeview_nodes_rtl_png = Url("treeview-nodes-rtl.png");
                public static readonly string treeview_nodes_png = Url("treeview-nodes.png");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Forest {
                private const string URLPATH = "~/Content/2013.2.611/Forest";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string editor_png = Url("editor.png");
                public static readonly string imagebrowser_png = Url("imagebrowser.png");
                public static readonly string loading_gif = Url("loading.gif");
                public static readonly string slider_h_gif = Url("slider-h.gif");
                public static readonly string slider_v_gif = Url("slider-v.gif");
                public static readonly string sprite_vertical_png = Url("sprite-vertical.png");
                public static readonly string sprite_png = Url("sprite.png");
                public static readonly string treeview_line_png = Url("treeview-line.png");
                public static readonly string treeview_nodes_rtl_png = Url("treeview-nodes-rtl.png");
                public static readonly string treeview_nodes_png = Url("treeview-nodes.png");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Hay {
                private const string URLPATH = "~/Content/2013.2.611/Hay";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string editor_png = Url("editor.png");
                public static readonly string imagebrowser_png = Url("imagebrowser.png");
                public static readonly string loading_gif = Url("loading.gif");
                public static readonly string slider_h_gif = Url("slider-h.gif");
                public static readonly string slider_v_gif = Url("slider-v.gif");
                public static readonly string sprite_vertical_png = Url("sprite-vertical.png");
                public static readonly string sprite_png = Url("sprite.png");
                public static readonly string treeview_line_png = Url("treeview-line.png");
                public static readonly string treeview_nodes_rtl_png = Url("treeview-nodes-rtl.png");
                public static readonly string treeview_nodes_png = Url("treeview-nodes.png");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Metro {
                private const string URLPATH = "~/Content/2013.2.611/Metro";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string editor_png = Url("editor.png");
                public static readonly string imagebrowser_png = Url("imagebrowser.png");
                public static readonly string loading_gif = Url("loading.gif");
                public static readonly string slider_h_gif = Url("slider-h.gif");
                public static readonly string slider_v_gif = Url("slider-v.gif");
                public static readonly string sprite_png = Url("sprite.png");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Office2007 {
                private const string URLPATH = "~/Content/2013.2.611/Office2007";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string editor_png = Url("editor.png");
                public static readonly string imagebrowser_png = Url("imagebrowser.png");
                public static readonly string loading_gif = Url("loading.gif");
                public static readonly string slider_h_gif = Url("slider-h.gif");
                public static readonly string slider_v_gif = Url("slider-v.gif");
                public static readonly string sprite_vertical_png = Url("sprite-vertical.png");
                public static readonly string sprite_png = Url("sprite.png");
                public static readonly string treeview_line_png = Url("treeview-line.png");
                public static readonly string treeview_nodes_rtl_png = Url("treeview-nodes-rtl.png");
                public static readonly string treeview_nodes_png = Url("treeview-nodes.png");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Office2010Black {
                private const string URLPATH = "~/Content/2013.2.611/Office2010Black";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string editor_png = Url("editor.png");
                public static readonly string imagebrowser_png = Url("imagebrowser.png");
                public static readonly string loading_gif = Url("loading.gif");
                public static readonly string slider_h_gif = Url("slider-h.gif");
                public static readonly string slider_v_gif = Url("slider-v.gif");
                public static readonly string sprite_vertical_png = Url("sprite-vertical.png");
                public static readonly string sprite_png = Url("sprite.png");
                public static readonly string treeview_line_png = Url("treeview-line.png");
                public static readonly string treeview_nodes_rtl_png = Url("treeview-nodes-rtl.png");
                public static readonly string treeview_nodes_png = Url("treeview-nodes.png");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Office2010Blue {
                private const string URLPATH = "~/Content/2013.2.611/Office2010Blue";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string editor_png = Url("editor.png");
                public static readonly string gradient_png = Url("gradient.png");
                public static readonly string imagebrowser_png = Url("imagebrowser.png");
                public static readonly string loading_gif = Url("loading.gif");
                public static readonly string slider_h_gif = Url("slider-h.gif");
                public static readonly string slider_v_gif = Url("slider-v.gif");
                public static readonly string sprite_vertical_png = Url("sprite-vertical.png");
                public static readonly string sprite_png = Url("sprite.png");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Office2010Silver {
                private const string URLPATH = "~/Content/2013.2.611/Office2010Silver";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string editor_png = Url("editor.png");
                public static readonly string gradient_png = Url("gradient.png");
                public static readonly string imagebrowser_png = Url("imagebrowser.png");
                public static readonly string loading_gif = Url("loading.gif");
                public static readonly string slider_h_gif = Url("slider-h.gif");
                public static readonly string slider_v_gif = Url("slider-v.gif");
                public static readonly string sprite_vertical_png = Url("sprite-vertical.png");
                public static readonly string sprite_png = Url("sprite.png");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Outlook {
                private const string URLPATH = "~/Content/2013.2.611/Outlook";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string editor_png = Url("editor.png");
                public static readonly string imagebrowser_png = Url("imagebrowser.png");
                public static readonly string loading_gif = Url("loading.gif");
                public static readonly string slider_h_gif = Url("slider-h.gif");
                public static readonly string slider_v_gif = Url("slider-v.gif");
                public static readonly string sprite_vertical_png = Url("sprite-vertical.png");
                public static readonly string sprite_png = Url("sprite.png");
                public static readonly string treeview_line_png = Url("treeview-line.png");
                public static readonly string treeview_nodes_rtl_png = Url("treeview-nodes-rtl.png");
                public static readonly string treeview_nodes_png = Url("treeview-nodes.png");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Simple {
                private const string URLPATH = "~/Content/2013.2.611/Simple";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string editor_png = Url("editor.png");
                public static readonly string imagebrowser_png = Url("imagebrowser.png");
                public static readonly string loading_gif = Url("loading.gif");
                public static readonly string slider_h_gif = Url("slider-h.gif");
                public static readonly string slider_v_gif = Url("slider-v.gif");
                public static readonly string sprite_png = Url("sprite.png");
                public static readonly string treeview_line_png = Url("treeview-line.png");
                public static readonly string treeview_nodes_rtl_png = Url("treeview-nodes-rtl.png");
                public static readonly string treeview_nodes_png = Url("treeview-nodes.png");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Sitefinity {
                private const string URLPATH = "~/Content/2013.2.611/Sitefinity";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string editor_png = Url("editor.png");
                public static readonly string imagebrowser_png = Url("imagebrowser.png");
                public static readonly string loading_gif = Url("loading.gif");
                public static readonly string slider_h_gif = Url("slider-h.gif");
                public static readonly string slider_v_gif = Url("slider-v.gif");
                public static readonly string sprite_vertical_png = Url("sprite-vertical.png");
                public static readonly string sprite_png = Url("sprite.png");
                public static readonly string treeview_line_png = Url("treeview-line.png");
                public static readonly string treeview_nodes_rtl_png = Url("treeview-nodes-rtl.png");
                public static readonly string treeview_nodes_png = Url("treeview-nodes.png");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Sunset {
                private const string URLPATH = "~/Content/2013.2.611/Sunset";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string editor_png = Url("editor.png");
                public static readonly string imagebrowser_png = Url("imagebrowser.png");
                public static readonly string loading_gif = Url("loading.gif");
                public static readonly string slider_h_gif = Url("slider-h.gif");
                public static readonly string slider_v_gif = Url("slider-v.gif");
                public static readonly string sprite_vertical_png = Url("sprite-vertical.png");
                public static readonly string sprite_png = Url("sprite.png");
                public static readonly string treeview_line_png = Url("treeview-line.png");
                public static readonly string treeview_nodes_rtl_png = Url("treeview-nodes-rtl.png");
                public static readonly string treeview_nodes_png = Url("treeview-nodes.png");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Telerik {
                private const string URLPATH = "~/Content/2013.2.611/Telerik";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string editor_png = Url("editor.png");
                public static readonly string imagebrowser_png = Url("imagebrowser.png");
                public static readonly string loading_gif = Url("loading.gif");
                public static readonly string slider_h_gif = Url("slider-h.gif");
                public static readonly string slider_v_gif = Url("slider-v.gif");
                public static readonly string sprite_vertical_png = Url("sprite-vertical.png");
                public static readonly string sprite_png = Url("sprite.png");
                public static readonly string treeview_line_png = Url("treeview-line.png");
                public static readonly string treeview_nodes_rtl_png = Url("treeview-nodes-rtl.png");
                public static readonly string treeview_nodes_png = Url("treeview-nodes.png");
            }
        
            public static readonly string telerik_black_min_css = Url("telerik.black.min.css");
            public static readonly string telerik_common_min_css = Url("telerik.common.min.css");
            public static readonly string telerik_default_min_css = Url("telerik.default.min.css");
            public static readonly string telerik_forest_min_css = Url("telerik.forest.min.css");
            public static readonly string telerik_hay_min_css = Url("telerik.hay.min.css");
            public static readonly string telerik_metro_min_css = Url("telerik.metro.min.css");
            public static readonly string telerik_office2007_min_css = Url("telerik.office2007.min.css");
            public static readonly string telerik_office2010black_min_css = Url("telerik.office2010black.min.css");
            public static readonly string telerik_office2010blue_min_css = Url("telerik.office2010blue.min.css");
            public static readonly string telerik_office2010silver_min_css = Url("telerik.office2010silver.min.css");
            public static readonly string telerik_outlook_min_css = Url("telerik.outlook.min.css");
            public static readonly string telerik_rtl_min_css = Url("telerik.rtl.min.css");
            public static readonly string telerik_simple_min_css = Url("telerik.simple.min.css");
            public static readonly string telerik_sitefinity_min_css = Url("telerik.sitefinity.min.css");
            public static readonly string telerik_sunset_min_css = Url("telerik.sunset.min.css");
            public static readonly string telerik_telerik_min_css = Url("telerik.telerik.min.css");
            public static readonly string telerik_transparent_min_css = Url("telerik.transparent.min.css");
            public static readonly string telerik_vista_min_css = Url("telerik.vista.min.css");
            public static readonly string telerik_web20_min_css = Url("telerik.web20.min.css");
            public static readonly string telerik_webblue_min_css = Url("telerik.webblue.min.css");
            public static readonly string telerik_windows7_min_css = Url("telerik.windows7.min.css");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Transparent {
                private const string URLPATH = "~/Content/2013.2.611/Transparent";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string active_png = Url("active.png");
                public static readonly string editor_png = Url("editor.png");
                public static readonly string gradient_png = Url("gradient.png");
                public static readonly string group_png = Url("group.png");
                public static readonly string hover_png = Url("hover.png");
                public static readonly string imagebrowser_png = Url("imagebrowser.png");
                public static readonly string loading_gif = Url("loading.gif");
                public static readonly string selected_png = Url("selected.png");
                public static readonly string slider_h_gif = Url("slider-h.gif");
                public static readonly string slider_v_gif = Url("slider-v.gif");
                public static readonly string sprite_vertical_png = Url("sprite-vertical.png");
                public static readonly string sprite_png = Url("sprite.png");
                public static readonly string toolbar_png = Url("toolbar.png");
                public static readonly string widget_png = Url("widget.png");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Vista {
                private const string URLPATH = "~/Content/2013.2.611/Vista";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string editor_png = Url("editor.png");
                public static readonly string imagebrowser_png = Url("imagebrowser.png");
                public static readonly string loading_gif = Url("loading.gif");
                public static readonly string slider_h_gif = Url("slider-h.gif");
                public static readonly string slider_v_gif = Url("slider-v.gif");
                public static readonly string sprite_vertical_png = Url("sprite-vertical.png");
                public static readonly string sprite_png = Url("sprite.png");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Web20 {
                private const string URLPATH = "~/Content/2013.2.611/Web20";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string editor_png = Url("editor.png");
                public static readonly string imagebrowser_png = Url("imagebrowser.png");
                public static readonly string loading_gif = Url("loading.gif");
                public static readonly string slider_h_gif = Url("slider-h.gif");
                public static readonly string slider_v_gif = Url("slider-v.gif");
                public static readonly string sprite_vertical_png = Url("sprite-vertical.png");
                public static readonly string sprite_png = Url("sprite.png");
                public static readonly string treeview_line_png = Url("treeview-line.png");
                public static readonly string treeview_nodes_rtl_png = Url("treeview-nodes-rtl.png");
                public static readonly string treeview_nodes_png = Url("treeview-nodes.png");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class WebBlue {
                private const string URLPATH = "~/Content/2013.2.611/WebBlue";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string editor_png = Url("editor.png");
                public static readonly string imagebrowser_png = Url("imagebrowser.png");
                public static readonly string loading_gif = Url("loading.gif");
                public static readonly string slider_h_gif = Url("slider-h.gif");
                public static readonly string slider_v_gif = Url("slider-v.gif");
                public static readonly string sprite_vertical_png = Url("sprite-vertical.png");
                public static readonly string sprite_png = Url("sprite.png");
                public static readonly string treeview_line_png = Url("treeview-line.png");
                public static readonly string treeview_nodes_rtl_png = Url("treeview-nodes-rtl.png");
                public static readonly string treeview_nodes_png = Url("treeview-nodes.png");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Windows7 {
                private const string URLPATH = "~/Content/2013.2.611/Windows7";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string editor_png = Url("editor.png");
                public static readonly string imagebrowser_png = Url("imagebrowser.png");
                public static readonly string loading_gif = Url("loading.gif");
                public static readonly string slider_h_gif = Url("slider-h.gif");
                public static readonly string slider_v_gif = Url("slider-v.gif");
                public static readonly string sprite_vertical_png = Url("sprite-vertical.png");
                public static readonly string sprite_png = Url("sprite.png");
            }
        
        }
    
        public static readonly string about_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/about.min.css") ? Url("about.min.css") : Url("about.css");
             
        public static readonly string bootstrap_theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap-theme.min.css") ? Url("bootstrap-theme.min.css") : Url("bootstrap-theme.css");
             
        public static readonly string bootstrap_theme_css_map = Url("bootstrap-theme.css.map");
        public static readonly string bootstrap_theme_min_css = Url("bootstrap-theme.min.css");
        public static readonly string bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.css") ? Url("bootstrap.min.css") : Url("bootstrap.css");
             
        public static readonly string bootstrap_css_map = Url("bootstrap.css.map");
        public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
        public static readonly string checkout_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/checkout.min.css") ? Url("checkout.min.css") : Url("checkout.css");
             
        public static readonly string checkout_success_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/checkout_success.min.css") ? Url("checkout_success.min.css") : Url("checkout_success.css");
             
        public static readonly string contact_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/contact.min.css") ? Url("contact.min.css") : Url("contact.css");
             
        public static readonly string customise_detail_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/customise_detail.min.css") ? Url("customise_detail.min.css") : Url("customise_detail.css");
             
        public static readonly string customise_list_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/customise_list.min.css") ? Url("customise_list.min.css") : Url("customise_list.css");
             
        public static readonly string edit_myacc_details_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/edit_myacc_details.min.css") ? Url("edit_myacc_details.min.css") : Url("edit_myacc_details.css");
             
        public static readonly string form_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/form.min.css") ? Url("form.min.css") : Url("form.css");
             
        public static readonly string myaccount_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/myaccount.min.css") ? Url("myaccount.min.css") : Url("myaccount.css");
             
        public static readonly string order_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/order.min.css") ? Url("order.min.css") : Url("order.css");
             
        public static readonly string orderhistory_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/orderhistory.min.css") ? Url("orderhistory.min.css") : Url("orderhistory.css");
             
        public static readonly string ordersummary_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/ordersummary.min.css") ? Url("ordersummary.min.css") : Url("ordersummary.css");
             
        public static readonly string proddetail_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/proddetail.min.css") ? Url("proddetail.min.css") : Url("proddetail.css");
             
        public static readonly string productlist_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/productlist.min.css") ? Url("productlist.min.css") : Url("productlist.css");
             
        public static readonly string shoppingbag_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/shoppingbag.min.css") ? Url("shoppingbag.min.css") : Url("shoppingbag.css");
             
        public static readonly string signin_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/signin.min.css") ? Url("signin.min.css") : Url("signin.css");
             
        public static readonly string Site_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Site.min.css") ? Url("Site.min.css") : Url("Site.css");
             
        public static readonly string SiteAdmin_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/SiteAdmin.min.css") ? Url("SiteAdmin.min.css") : Url("SiteAdmin.css");
             
        public static readonly string sticky_footer_navbar_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/sticky-footer-navbar.min.css") ? Url("sticky-footer-navbar.min.css") : Url("sticky-footer-navbar.css");
             
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class themes {
            private const string URLPATH = "~/Content/themes";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class @base {
                private const string URLPATH = "~/Content/themes/base";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class images {
                    private const string URLPATH = "~/Content/themes/base/images";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string ui_bg_flat_0_aaaaaa_40x100_png = Url("ui-bg_flat_0_aaaaaa_40x100.png");
                    public static readonly string ui_bg_flat_75_ffffff_40x100_png = Url("ui-bg_flat_75_ffffff_40x100.png");
                    public static readonly string ui_bg_glass_55_fbf9ee_1x400_png = Url("ui-bg_glass_55_fbf9ee_1x400.png");
                    public static readonly string ui_bg_glass_65_ffffff_1x400_png = Url("ui-bg_glass_65_ffffff_1x400.png");
                    public static readonly string ui_bg_glass_75_dadada_1x400_png = Url("ui-bg_glass_75_dadada_1x400.png");
                    public static readonly string ui_bg_glass_75_e6e6e6_1x400_png = Url("ui-bg_glass_75_e6e6e6_1x400.png");
                    public static readonly string ui_bg_glass_95_fef1ec_1x400_png = Url("ui-bg_glass_95_fef1ec_1x400.png");
                    public static readonly string ui_bg_highlight_soft_75_cccccc_1x100_png = Url("ui-bg_highlight-soft_75_cccccc_1x100.png");
                    public static readonly string ui_icons_222222_256x240_png = Url("ui-icons_222222_256x240.png");
                    public static readonly string ui_icons_2e83ff_256x240_png = Url("ui-icons_2e83ff_256x240.png");
                    public static readonly string ui_icons_454545_256x240_png = Url("ui-icons_454545_256x240.png");
                    public static readonly string ui_icons_888888_256x240_png = Url("ui-icons_888888_256x240.png");
                    public static readonly string ui_icons_cd0a0a_256x240_png = Url("ui-icons_cd0a0a_256x240.png");
                }
            
                public static readonly string jquery_ui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui.min.css") ? Url("jquery-ui.min.css") : Url("jquery-ui.css");
                     
                public static readonly string jquery_ui_accordion_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.accordion.min.css") ? Url("jquery.ui.accordion.min.css") : Url("jquery.ui.accordion.css");
                     
                public static readonly string jquery_ui_all_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.all.min.css") ? Url("jquery.ui.all.min.css") : Url("jquery.ui.all.css");
                     
                public static readonly string jquery_ui_autocomplete_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.autocomplete.min.css") ? Url("jquery.ui.autocomplete.min.css") : Url("jquery.ui.autocomplete.css");
                     
                public static readonly string jquery_ui_base_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.base.min.css") ? Url("jquery.ui.base.min.css") : Url("jquery.ui.base.css");
                     
                public static readonly string jquery_ui_button_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.button.min.css") ? Url("jquery.ui.button.min.css") : Url("jquery.ui.button.css");
                     
                public static readonly string jquery_ui_core_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.core.min.css") ? Url("jquery.ui.core.min.css") : Url("jquery.ui.core.css");
                     
                public static readonly string jquery_ui_datepicker_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.datepicker.min.css") ? Url("jquery.ui.datepicker.min.css") : Url("jquery.ui.datepicker.css");
                     
                public static readonly string jquery_ui_dialog_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.dialog.min.css") ? Url("jquery.ui.dialog.min.css") : Url("jquery.ui.dialog.css");
                     
                public static readonly string jquery_ui_progressbar_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.progressbar.min.css") ? Url("jquery.ui.progressbar.min.css") : Url("jquery.ui.progressbar.css");
                     
                public static readonly string jquery_ui_resizable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.resizable.min.css") ? Url("jquery.ui.resizable.min.css") : Url("jquery.ui.resizable.css");
                     
                public static readonly string jquery_ui_selectable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.selectable.min.css") ? Url("jquery.ui.selectable.min.css") : Url("jquery.ui.selectable.css");
                     
                public static readonly string jquery_ui_slider_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.slider.min.css") ? Url("jquery.ui.slider.min.css") : Url("jquery.ui.slider.css");
                     
                public static readonly string jquery_ui_tabs_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.tabs.min.css") ? Url("jquery.ui.tabs.min.css") : Url("jquery.ui.tabs.css");
                     
                public static readonly string jquery_ui_theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.theme.min.css") ? Url("jquery.ui.theme.min.css") : Url("jquery.ui.theme.css");
                     
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class minified {
                    private const string URLPATH = "~/Content/themes/base/minified";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class images {
                        private const string URLPATH = "~/Content/themes/base/minified/images";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string ui_bg_flat_0_aaaaaa_40x100_png = Url("ui-bg_flat_0_aaaaaa_40x100.png");
                        public static readonly string ui_bg_flat_75_ffffff_40x100_png = Url("ui-bg_flat_75_ffffff_40x100.png");
                        public static readonly string ui_bg_glass_55_fbf9ee_1x400_png = Url("ui-bg_glass_55_fbf9ee_1x400.png");
                        public static readonly string ui_bg_glass_65_ffffff_1x400_png = Url("ui-bg_glass_65_ffffff_1x400.png");
                        public static readonly string ui_bg_glass_75_dadada_1x400_png = Url("ui-bg_glass_75_dadada_1x400.png");
                        public static readonly string ui_bg_glass_75_e6e6e6_1x400_png = Url("ui-bg_glass_75_e6e6e6_1x400.png");
                        public static readonly string ui_bg_glass_95_fef1ec_1x400_png = Url("ui-bg_glass_95_fef1ec_1x400.png");
                        public static readonly string ui_bg_highlight_soft_75_cccccc_1x100_png = Url("ui-bg_highlight-soft_75_cccccc_1x100.png");
                        public static readonly string ui_icons_222222_256x240_png = Url("ui-icons_222222_256x240.png");
                        public static readonly string ui_icons_2e83ff_256x240_png = Url("ui-icons_2e83ff_256x240.png");
                        public static readonly string ui_icons_454545_256x240_png = Url("ui-icons_454545_256x240.png");
                        public static readonly string ui_icons_888888_256x240_png = Url("ui-icons_888888_256x240.png");
                        public static readonly string ui_icons_cd0a0a_256x240_png = Url("ui-icons_cd0a0a_256x240.png");
                    }
                
                    public static readonly string jquery_ui_min_css = Url("jquery-ui.min.css");
                    public static readonly string jquery_ui_accordion_min_css = Url("jquery.ui.accordion.min.css");
                    public static readonly string jquery_ui_autocomplete_min_css = Url("jquery.ui.autocomplete.min.css");
                    public static readonly string jquery_ui_button_min_css = Url("jquery.ui.button.min.css");
                    public static readonly string jquery_ui_core_min_css = Url("jquery.ui.core.min.css");
                    public static readonly string jquery_ui_datepicker_min_css = Url("jquery.ui.datepicker.min.css");
                    public static readonly string jquery_ui_dialog_min_css = Url("jquery.ui.dialog.min.css");
                    public static readonly string jquery_ui_progressbar_min_css = Url("jquery.ui.progressbar.min.css");
                    public static readonly string jquery_ui_resizable_min_css = Url("jquery.ui.resizable.min.css");
                    public static readonly string jquery_ui_selectable_min_css = Url("jquery.ui.selectable.min.css");
                    public static readonly string jquery_ui_slider_min_css = Url("jquery.ui.slider.min.css");
                    public static readonly string jquery_ui_tabs_min_css = Url("jquery.ui.tabs.min.css");
                    public static readonly string jquery_ui_theme_min_css = Url("jquery.ui.theme.min.css");
                }
            
            }
        
        }
    
        public static readonly string trending_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/trending.min.css") ? Url("trending.min.css") : Url("trending.css");
             
        public static readonly string ttt_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/ttt.min.css") ? Url("ttt.min.css") : Url("ttt.css");
             
        public static readonly string wishlist_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/wishlist.min.css") ? Url("wishlist.min.css") : Url("wishlist.css");
             
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Images {
        private const string URLPATH = "~/Images";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class about {
            private const string URLPATH = "~/Images/about";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string lines_png = Url("lines.png");
            public static readonly string pic1_jpg = Url("pic1.jpg");
            public static readonly string pic2_jpg = Url("pic2.jpg");
            public static readonly string sil1_png = Url("sil1.png");
            public static readonly string sil2_png = Url("sil2.png");
            public static readonly string title_png = Url("title.png");
        }
    
        public static readonly string accent_png = Url("accent.png");
        public static readonly string allshoes_gif = Url("allshoes.gif");
        public static readonly string allshoes_s2_gif = Url("allshoes_s2.gif");
        public static readonly string arrow_next_gif = Url("arrow_next.gif");
        public static readonly string arrow_prev_gif = Url("arrow_prev.gif");
        public static readonly string arrowdown_gif = Url("arrowdown.gif");
        public static readonly string arrowdown2_gif = Url("arrowdown2.gif");
        public static readonly string arrowrecentwish_gif = Url("arrowrecentwish.gif");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class ballerina {
            private const string URLPATH = "~/Images/ballerina";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string icon_ballerina_jpg = Url("icon_ballerina.jpg");
        }
    
        public static readonly string ballerina_gif = Url("ballerina.gif");
        public static readonly string ballerina_s2_gif = Url("ballerina_s2.gif");
        public static readonly string bullet_png = Url("bullet.png");
        public static readonly string button_search_png = Url("button_search.png");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Category {
            private const string URLPATH = "~/Images/Category";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string allshoes_gif = Url("allshoes.gif");
            public static readonly string allshoes_s2_gif = Url("allshoes_s2.gif");
            public static readonly string ballerina_gif = Url("ballerina.gif");
            public static readonly string ballerina_s2_gif = Url("ballerina_s2.gif");
            public static readonly string blank_gif = Url("blank.gif");
            public static readonly string blank_s2_gif = Url("blank_s2.gif");
            public static readonly string flats_gif = Url("flats.gif");
            public static readonly string flats_s2_gif = Url("flats_s2.gif");
            public static readonly string kaleidoscope_r1_c1_gif = Url("kaleidoscope_r1_c1.gif");
            public static readonly string kaleidoscope_r1_c1_s2_gif = Url("kaleidoscope_r1_c1_s2.gif");
            public static readonly string peeptoes_gif = Url("peeptoes.gif");
            public static readonly string peeptoes_s2_gif = Url("peeptoes_s2.gif");
            public static readonly string platform_gif = Url("platform.gif");
            public static readonly string platform_s2_gif = Url("platform_s2.gif");
            public static readonly string pumps_gif = Url("pumps.gif");
            public static readonly string pumps_s2_gif = Url("pumps_s2.gif");
            public static readonly string sandals_gif = Url("sandals.gif");
            public static readonly string sandals_s2_gif = Url("sandals_s2.gif");
            public static readonly string spacer_gif = Url("spacer.gif");
            public static readonly string wedges_gif = Url("wedges.gif");
            public static readonly string wedges_s2_gif = Url("wedges_s2.gif");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class contact {
            private const string URLPATH = "~/Images/contact";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string pic1_jpg = Url("pic1.jpg");
            public static readonly string title_png = Url("title.png");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Customize {
            private const string URLPATH = "~/Images/Customize";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class ShoeColour {
                private const string URLPATH = "~/Images/Customize/ShoeColour";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string PeepToe_Pump_3_Black_1_jpg = Url("PeepToe_Pump_3_Black_1.jpg");
                public static readonly string PeepToe_Pump_3_Blue_2_jpg = Url("PeepToe_Pump_3_Blue_2.jpg");
                public static readonly string PeepToe_Pump_3_Brown_7_jpg = Url("PeepToe_Pump_3_Brown_7.jpg");
                public static readonly string PeepToe_Pump_3_Cyan_11_jpg = Url("PeepToe_Pump_3_Cyan_11.jpg");
                public static readonly string PeepToe_Pump_3_Gold_9_jpg = Url("PeepToe_Pump_3_Gold_9.jpg");
                public static readonly string PeepToe_Pump_3_Green_3_jpg = Url("PeepToe_Pump_3_Green_3.jpg");
                public static readonly string PeepToe_Pump_3_Magenta_12_jpg = Url("PeepToe_Pump_3_Magenta_12.jpg");
                public static readonly string PeepToe_Pump_3_Purple_8_jpg = Url("PeepToe_Pump_3_Purple_8.jpg");
                public static readonly string PeepToe_Pump_3_Red_4_jpg = Url("PeepToe_Pump_3_Red_4.jpg");
                public static readonly string PeepToe_Pump_3_Silver_10_jpg = Url("PeepToe_Pump_3_Silver_10.jpg");
                public static readonly string PeepToe_Pump_3_turquoise_6_jpg = Url("PeepToe_Pump_3_turquoise_6.jpg");
                public static readonly string PeepToe_Pump_3_Yellow_5_jpg = Url("PeepToe_Pump_3_Yellow_5.jpg");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class ShoeDetails {
                private const string URLPATH = "~/Images/Customize/ShoeDetails";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string PeepToe_Pump_3_Main_Black_1_jpg = Url("PeepToe_Pump_3_Main_Black_1.jpg");
                public static readonly string PeepToe_Pump_3_Main_Black_2_jpg = Url("PeepToe_Pump_3_Main_Black_2.jpg");
                public static readonly string PeepToe_Pump_3_Main_Black_3_jpg = Url("PeepToe_Pump_3_Main_Black_3.jpg");
                public static readonly string PeepToe_Pump_3_Main_Black_4_jpg = Url("PeepToe_Pump_3_Main_Black_4.jpg");
                public static readonly string PeepToe_Pump_3_Sub_Black_1_jpg = Url("PeepToe_Pump_3_Sub_Black_1.jpg");
                public static readonly string PeepToe_Pump_3_Sub_Black_2_jpg = Url("PeepToe_Pump_3_Sub_Black_2.jpg");
                public static readonly string PeepToe_Pump_3_Sub_Black_3_jpg = Url("PeepToe_Pump_3_Sub_Black_3.jpg");
                public static readonly string PeepToe_Pump_3_Sub_Black_4_jpg = Url("PeepToe_Pump_3_Sub_Black_4.jpg");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class ShoeStyle {
                private const string URLPATH = "~/Images/Customize/ShoeStyle";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string PeepToe_MaryJane_Main_jpg = Url("PeepToe_MaryJane_Main.jpg");
                public static readonly string PeepToe_Pump_Main_jpg = Url("PeepToe_Pump_Main.jpg");
                public static readonly string PeepToe_Pump_Sub_jpg = Url("PeepToe_Pump_Sub.jpg");
                public static readonly string PeepToe_Slingback_Main_jpg = Url("PeepToe_Slingback_Main.jpg");
                public static readonly string PointedToe_MaryJane_Main_jpg = Url("PointedToe_MaryJane_Main.jpg");
                public static readonly string PointedToe_Pump_Main_jpg = Url("PointedToe_Pump_Main.jpg");
                public static readonly string PointedToe_Slingback_Main_jpg = Url("PointedToe_Slingback_Main.jpg");
                public static readonly string RoundedToe_MaryJane_Main_jpg = Url("RoundedToe_MaryJane_Main.jpg");
                public static readonly string RoundedToe_Pump_Main_jpg = Url("RoundedToe_Pump_Main.jpg");
                public static readonly string RoundedToe_Slingback_Main_jpg = Url("RoundedToe_Slingback_Main.jpg");
            }
        
        }
    
        public static readonly string dotted_ver_gif = Url("dotted_ver.gif");
        public static readonly string favicon_ico = Url("favicon.ico");
        public static readonly string flat_gif = Url("flat.gif");
        public static readonly string flat_s2_gif = Url("flat_s2.gif");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class flats {
            private const string URLPATH = "~/Images/flats";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string _5060_0007_A_jpg = Url("5060-0007_A.jpg");
            public static readonly string _5060_0007_B_jpg = Url("5060-0007_B.jpg");
            public static readonly string _5060_0007_L_1_jpg = Url("5060-0007_L_1.jpg");
            public static readonly string _5060_0007_L_2_jpg = Url("5060-0007_L_2.jpg");
            public static readonly string _5060_0007_L_3_jpg = Url("5060-0007_L_3.jpg");
            public static readonly string _5060_0007_L_4_jpg = Url("5060-0007_L_4.jpg");
            public static readonly string _5060_0007_S_1_jpg = Url("5060-0007_S_1.jpg");
            public static readonly string _5060_0007_S_2_jpg = Url("5060-0007_S_2.jpg");
            public static readonly string _5060_0007_S_3_jpg = Url("5060-0007_S_3.jpg");
            public static readonly string _5060_0007_S_4_jpg = Url("5060-0007_S_4.jpg");
            public static readonly string icon_flats_jpg = Url("icon_flats.jpg");
        }
    
        public static readonly string footer_icon_fb_gif = Url("footer_icon_fb.gif");
        public static readonly string footer_icon_google_gif = Url("footer_icon_google.gif");
        public static readonly string footer_icon_pinterest_gif = Url("footer_icon_pinterest.gif");
        public static readonly string footer_icon_tumblr_gif = Url("footer_icon_tumblr.gif");
        public static readonly string footer_icon_twit_gif = Url("footer_icon_twit.gif");
        public static readonly string freeshipping_icon_gif = Url("freeshipping_icon.gif");
        public static readonly string heroAccent_png = Url("heroAccent.png");
        public static readonly string horline_gif = Url("horline.gif");
        public static readonly string icon_shoppingbag_gif = Url("icon_shoppingbag.gif");
        public static readonly string kaleidoscope_r1_c1_gif = Url("kaleidoscope_r1_c1.gif");
        public static readonly string kaleidoscope_r1_c1_s2_gif = Url("kaleidoscope_r1_c1_s2.gif");
        public static readonly string main_nav_dottedline_gif = Url("main_nav_dottedline.gif");
        public static readonly string main_pic1_jpg = Url("main_pic1.jpg");
        public static readonly string main_pic2_jpg = Url("main_pic2.jpg");
        public static readonly string main_pic3_jpg = Url("main_pic3.jpg");
        public static readonly string main_pic4_jpg = Url("main_pic4.jpg");
        public static readonly string main_pic5_jpg = Url("main_pic5.jpg");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class myaccount {
            private const string URLPATH = "~/Images/myaccount";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string mastercard_icon_gif = Url("mastercard_icon.gif");
            public static readonly string visa_icon_gif = Url("visa_icon.gif");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class order {
            private const string URLPATH = "~/Images/order";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string lines_png = Url("lines.png");
            public static readonly string pic1_jpg = Url("pic1.jpg");
            public static readonly string pic2_jpg = Url("pic2.jpg");
            public static readonly string sil1_png = Url("sil1.png");
            public static readonly string sil2_png = Url("sil2.png");
            public static readonly string title_png = Url("title.png");
        }
    
        public static readonly string orderedList0_png = Url("orderedList0.png");
        public static readonly string orderedList1_png = Url("orderedList1.png");
        public static readonly string orderedList2_png = Url("orderedList2.png");
        public static readonly string orderedList3_png = Url("orderedList3.png");
        public static readonly string orderedList4_png = Url("orderedList4.png");
        public static readonly string orderedList5_png = Url("orderedList5.png");
        public static readonly string orderedList6_png = Url("orderedList6.png");
        public static readonly string orderedList7_png = Url("orderedList7.png");
        public static readonly string orderedList8_png = Url("orderedList8.png");
        public static readonly string orderedList9_png = Url("orderedList9.png");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class peeptoes {
            private const string URLPATH = "~/Images/peeptoes";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string _6063_0512_A_jpg = Url("6063-0512_A.jpg");
            public static readonly string _6063_0512_B_jpg = Url("6063-0512_B.jpg");
            public static readonly string _6063_0512_L_1_jpg = Url("6063-0512_L_1.jpg");
            public static readonly string _6063_0512_L_2_jpg = Url("6063-0512_L_2.jpg");
            public static readonly string _6063_0512_L_3_jpg = Url("6063-0512_L_3.jpg");
            public static readonly string _6063_0512_L_4_jpg = Url("6063-0512_L_4.jpg");
            public static readonly string _6063_0512_S_1_jpg = Url("6063-0512_S_1.jpg");
            public static readonly string _6063_0512_S_2_jpg = Url("6063-0512_S_2.jpg");
            public static readonly string _6063_0512_S_3_jpg = Url("6063-0512_S_3.jpg");
            public static readonly string _6063_0512_S_4_jpg = Url("6063-0512_S_4.jpg");
            public static readonly string _6063_0904_A_jpg = Url("6063-0904_A.jpg");
            public static readonly string _6063_0904_B_jpg = Url("6063-0904_B.jpg");
            public static readonly string _6063_0904_L_1_jpg = Url("6063-0904_L_1.jpg");
            public static readonly string _6063_0904_L_2_jpg = Url("6063-0904_L_2.jpg");
            public static readonly string _6063_0904_L_3_jpg = Url("6063-0904_L_3.jpg");
            public static readonly string _6063_0904_L_4_jpg = Url("6063-0904_L_4.jpg");
            public static readonly string _6063_0904_S_1_jpg = Url("6063-0904_S_1.jpg");
            public static readonly string _6063_0904_S_2_jpg = Url("6063-0904_S_2.jpg");
            public static readonly string _6063_0904_S_3_jpg = Url("6063-0904_S_3.jpg");
            public static readonly string _6063_0904_S_4_jpg = Url("6063-0904_S_4.jpg");
            public static readonly string _6063_0912_A_jpg = Url("6063-0912_A.jpg");
            public static readonly string _6063_0912_B_jpg = Url("6063-0912_B.jpg");
            public static readonly string _6063_0912_L_1_jpg = Url("6063-0912_L_1.jpg");
            public static readonly string _6063_0912_L_2_jpg = Url("6063-0912_L_2.jpg");
            public static readonly string _6063_0912_L_3_jpg = Url("6063-0912_L_3.jpg");
            public static readonly string _6063_0912_L_4_jpg = Url("6063-0912_L_4.jpg");
            public static readonly string _6063_0912_S_1_jpg = Url("6063-0912_S_1.jpg");
            public static readonly string _6063_0912_S_2_jpg = Url("6063-0912_S_2.jpg");
            public static readonly string _6063_0912_S_3_jpg = Url("6063-0912_S_3.jpg");
            public static readonly string _6063_0912_S_4_jpg = Url("6063-0912_S_4.jpg");
            public static readonly string EXTRA_jpg = Url("EXTRA.jpg");
            public static readonly string icon_peeptoes_jpg = Url("icon_peeptoes.jpg");
        }
    
        public static readonly string peeptoes_gif = Url("peeptoes.gif");
        public static readonly string peeptoes_s2_gif = Url("peeptoes_s2.gif");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class platform {
            private const string URLPATH = "~/Images/platform";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string icon_platform_jpg = Url("icon_platform.jpg");
        }
    
        public static readonly string platform_gif = Url("platform.gif");
        public static readonly string platform_s2_gif = Url("platform_s2.gif");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class pumps {
            private const string URLPATH = "~/Images/pumps";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string _6013_0113_A_jpg = Url("6013-0113_A.jpg");
            public static readonly string _6013_0113_B_jpg = Url("6013-0113_B.jpg");
            public static readonly string _6013_0113_L_1_jpg = Url("6013-0113_L_1.jpg");
            public static readonly string _6013_0113_L_2_jpg = Url("6013-0113_L_2.jpg");
            public static readonly string _6013_0113_L_3_jpg = Url("6013-0113_L_3.jpg");
            public static readonly string _6013_0113_L_4_jpg = Url("6013-0113_L_4.jpg");
            public static readonly string _6013_0113_S_1_jpg = Url("6013-0113_S_1.jpg");
            public static readonly string _6013_0113_S_2_jpg = Url("6013-0113_S_2.jpg");
            public static readonly string _6013_0113_S_3_jpg = Url("6013-0113_S_3.jpg");
            public static readonly string _6013_0113_S_4_jpg = Url("6013-0113_S_4.jpg");
            public static readonly string _6013_0213_A_jpg = Url("6013-0213_A.jpg");
            public static readonly string _6013_0213_B_jpg = Url("6013-0213_B.jpg");
            public static readonly string _6013_0213_L_1_jpg = Url("6013-0213_L_1.jpg");
            public static readonly string _6013_0213_L_2_jpg = Url("6013-0213_L_2.jpg");
            public static readonly string _6013_0213_L_3_jpg = Url("6013-0213_L_3.jpg");
            public static readonly string _6013_0213_L_4_jpg = Url("6013-0213_L_4.jpg");
            public static readonly string _6013_0213_S_1_jpg = Url("6013-0213_S_1.jpg");
            public static readonly string _6013_0213_S_2_jpg = Url("6013-0213_S_2.jpg");
            public static readonly string _6013_0213_S_3_jpg = Url("6013-0213_S_3.jpg");
            public static readonly string _6013_0213_S_4_jpg = Url("6013-0213_S_4.jpg");
            public static readonly string _6013_0613_A_jpg = Url("6013-0613_A.jpg");
            public static readonly string _6013_0613_B_jpg = Url("6013-0613_B.jpg");
            public static readonly string _6013_0613_L_1_jpg = Url("6013-0613_L_1.jpg");
            public static readonly string _6013_0613_L_2_jpg = Url("6013-0613_L_2.jpg");
            public static readonly string _6013_0613_L_3_jpg = Url("6013-0613_L_3.jpg");
            public static readonly string _6013_0613_L_4_jpg = Url("6013-0613_L_4.jpg");
            public static readonly string _6013_0613_S_1_jpg = Url("6013-0613_S_1.jpg");
            public static readonly string _6013_0613_S_2_jpg = Url("6013-0613_S_2.jpg");
            public static readonly string _6013_0613_S_3_jpg = Url("6013-0613_S_3.jpg");
            public static readonly string _6013_0613_S_4_jpg = Url("6013-0613_S_4.jpg");
            public static readonly string _6013_0713_A_jpg = Url("6013-0713_A.jpg");
            public static readonly string _6013_0713_B_jpg = Url("6013-0713_B.jpg");
            public static readonly string _6013_0713_L_1_jpg = Url("6013-0713_L_1.jpg");
            public static readonly string _6013_0713_L_2_jpg = Url("6013-0713_L_2.jpg");
            public static readonly string _6013_0713_L_3_jpg = Url("6013-0713_L_3.jpg");
            public static readonly string _6013_0713_L_4_jpg = Url("6013-0713_L_4.jpg");
            public static readonly string _6013_0713_S_1_jpg = Url("6013-0713_S_1.jpg");
            public static readonly string _6013_0713_S_2_jpg = Url("6013-0713_S_2.jpg");
            public static readonly string _6013_0713_S_3_jpg = Url("6013-0713_S_3.jpg");
            public static readonly string _6013_0713_S_4_jpg = Url("6013-0713_S_4.jpg");
            public static readonly string _6013_0913_A_jpg = Url("6013-0913_A.jpg");
            public static readonly string _6013_0913_B_jpg = Url("6013-0913_B.jpg");
            public static readonly string _6013_0913_L_1_jpg = Url("6013-0913_L_1.jpg");
            public static readonly string _6013_0913_L_2_jpg = Url("6013-0913_L_2.jpg");
            public static readonly string _6013_0913_L_3_jpg = Url("6013-0913_L_3.jpg");
            public static readonly string _6013_0913_L_4_jpg = Url("6013-0913_L_4.jpg");
            public static readonly string _6013_0913_S_1_jpg = Url("6013-0913_S_1.jpg");
            public static readonly string _6013_0913_S_2_jpg = Url("6013-0913_S_2.jpg");
            public static readonly string _6013_0913_S_3_jpg = Url("6013-0913_S_3.jpg");
            public static readonly string _6013_0913_S_4_jpg = Url("6013-0913_S_4.jpg");
            public static readonly string _6013_1113_A_jpg = Url("6013-1113_A.jpg");
            public static readonly string _6013_1113_B_jpg = Url("6013-1113_B.jpg");
            public static readonly string _6013_1113_L_1_jpg = Url("6013-1113_L_1.jpg");
            public static readonly string _6013_1113_L_2_jpg = Url("6013-1113_L_2.jpg");
            public static readonly string _6013_1113_L_3_jpg = Url("6013-1113_L_3.jpg");
            public static readonly string _6013_1113_L_4_jpg = Url("6013-1113_L_4.jpg");
            public static readonly string _6013_1113_S_1_jpg = Url("6013-1113_S_1.jpg");
            public static readonly string _6013_1113_S_2_jpg = Url("6013-1113_S_2.jpg");
            public static readonly string _6013_1113_S_3_jpg = Url("6013-1113_S_3.jpg");
            public static readonly string _6013_1113_S_4_jpg = Url("6013-1113_S_4.jpg");
            public static readonly string _6013_1117_A_jpg = Url("6013-1117_A.jpg");
            public static readonly string _6013_1117_B_jpg = Url("6013-1117_B.jpg");
            public static readonly string _6013_1117_L_1_jpg = Url("6013-1117_L_1.jpg");
            public static readonly string _6013_1117_L_2_jpg = Url("6013-1117_L_2.jpg");
            public static readonly string _6013_1117_L_3_jpg = Url("6013-1117_L_3.jpg");
            public static readonly string _6013_1117_L_4_jpg = Url("6013-1117_L_4.jpg");
            public static readonly string _6013_1117_S_1_jpg = Url("6013-1117_S_1.jpg");
            public static readonly string _6013_1117_S_2_jpg = Url("6013-1117_S_2.jpg");
            public static readonly string _6013_1117_S_3_jpg = Url("6013-1117_S_3.jpg");
            public static readonly string _6013_1117_S_4_jpg = Url("6013-1117_S_4.jpg");
            public static readonly string _6013_1813_A_jpg = Url("6013-1813_A.jpg");
            public static readonly string _6013_1813_B_jpg = Url("6013-1813_B.jpg");
            public static readonly string _6013_1813_L_1_jpg = Url("6013-1813_L_1.jpg");
            public static readonly string _6013_1813_L_2_jpg = Url("6013-1813_L_2.jpg");
            public static readonly string _6013_1813_L_3_jpg = Url("6013-1813_L_3.jpg");
            public static readonly string _6013_1813_L_4_jpg = Url("6013-1813_L_4.jpg");
            public static readonly string _6013_1813_S_1_jpg = Url("6013-1813_S_1.jpg");
            public static readonly string _6013_1813_S_2_jpg = Url("6013-1813_S_2.jpg");
            public static readonly string _6013_1813_S_3_jpg = Url("6013-1813_S_3.jpg");
            public static readonly string _6013_1813_S_4_jpg = Url("6013-1813_S_4.jpg");
        }
    
        public static readonly string pumps_gif = Url("pumps.gif");
        public static readonly string pumps_s2_gif = Url("pumps_s2.gif");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class sandals {
            private const string URLPATH = "~/Images/sandals";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string _5060_0502_A_jpg = Url("5060-0502_A.jpg");
            public static readonly string _5060_0502_B_jpg = Url("5060-0502_B.jpg");
            public static readonly string _5060_0502_L_1_jpg = Url("5060-0502_L_1.jpg");
            public static readonly string _5060_0502_L_2_jpg = Url("5060-0502_L_2.jpg");
            public static readonly string _5060_0502_L_3_jpg = Url("5060-0502_L_3.jpg");
            public static readonly string _5060_0502_L_4_jpg = Url("5060-0502_L_4.jpg");
            public static readonly string _5060_0502_S_1_jpg = Url("5060-0502_S_1.jpg");
            public static readonly string _5060_0502_S_2_jpg = Url("5060-0502_S_2.jpg");
            public static readonly string _5060_0502_S_3_jpg = Url("5060-0502_S_3.jpg");
            public static readonly string _5060_0502_S_4_jpg = Url("5060-0502_S_4.jpg");
            public static readonly string _5060_0702_A_jpg = Url("5060-0702_A.jpg");
            public static readonly string _5060_0702_B_jpg = Url("5060-0702_B.jpg");
            public static readonly string _5060_0702_L_1_jpg = Url("5060-0702_L_1.jpg");
            public static readonly string _5060_0702_L_2_jpg = Url("5060-0702_L_2.jpg");
            public static readonly string _5060_0702_L_3_jpg = Url("5060-0702_L_3.jpg");
            public static readonly string _5060_0702_L_4_jpg = Url("5060-0702_L_4.jpg");
            public static readonly string _5060_0702_S_1_jpg = Url("5060-0702_S_1.jpg");
            public static readonly string _5060_0702_S_2_jpg = Url("5060-0702_S_2.jpg");
            public static readonly string _5060_0702_S_3_jpg = Url("5060-0702_S_3.jpg");
            public static readonly string _5060_0702_S_4_jpg = Url("5060-0702_S_4.jpg");
            public static readonly string _5060_0906_A_jpg = Url("5060-0906_A.jpg");
            public static readonly string _5060_0906_B_jpg = Url("5060-0906_B.jpg");
            public static readonly string _5060_0906_L_1_jpg = Url("5060-0906_L_1.jpg");
            public static readonly string _5060_0906_L_2_jpg = Url("5060-0906_L_2.jpg");
            public static readonly string _5060_0906_L_3_jpg = Url("5060-0906_L_3.jpg");
            public static readonly string _5060_0906_L_4_jpg = Url("5060-0906_L_4.jpg");
            public static readonly string _5060_0906_S_1_jpg = Url("5060-0906_S_1.jpg");
            public static readonly string _5060_0906_S_2_jpg = Url("5060-0906_S_2.jpg");
            public static readonly string _5060_0906_S_3_jpg = Url("5060-0906_S_3.jpg");
            public static readonly string _5060_0906_S_4_jpg = Url("5060-0906_S_4.jpg");
            public static readonly string _5060_1102_A_jpg = Url("5060-1102_A.jpg");
            public static readonly string _5060_1102_B_jpg = Url("5060-1102_B.jpg");
            public static readonly string _5060_1102_L_1_jpg = Url("5060-1102_L_1.jpg");
            public static readonly string _5060_1102_L_2_jpg = Url("5060-1102_L_2.jpg");
            public static readonly string _5060_1102_L_3_jpg = Url("5060-1102_L_3.jpg");
            public static readonly string _5060_1102_L_4_jpg = Url("5060-1102_L_4.jpg");
            public static readonly string _5060_1102_S_1_jpg = Url("5060-1102_S_1.jpg");
            public static readonly string _5060_1102_S_2_jpg = Url("5060-1102_S_2.jpg");
            public static readonly string _5060_1102_S_3_jpg = Url("5060-1102_S_3.jpg");
            public static readonly string _5060_1102_S_4_jpg = Url("5060-1102_S_4.jpg");
            public static readonly string icon_sandals_jpg = Url("icon_sandals.jpg");
        }
    
        public static readonly string sandals_gif = Url("sandals.gif");
        public static readonly string sandals_s2_gif = Url("sandals_s2.gif");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class signin {
            private const string URLPATH = "~/Images/signin";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string facebook_sign_in_png = Url("facebook-sign-in.png");
            public static readonly string pic1_jpg = Url("pic1.jpg");
        }
    
        public static readonly string spacer_gif = Url("spacer.gif");
        public static readonly string startcustom_button_gif = Url("startcustom_button.gif");
        public static readonly string tagline_gif = Url("tagline.gif");
        public static readonly string totetotoe_logo_gif = Url("totetotoe_logo.gif");
        public static readonly string totetotoe_logo_sizeref_gif = Url("totetotoe_logo_sizeref.gif");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class trending {
            private const string URLPATH = "~/Images/trending";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string lines1_png = Url("lines1.png");
            public static readonly string lines2_png = Url("lines2.png");
            public static readonly string pic1_jpg = Url("pic1.jpg");
            public static readonly string pic2_jpg = Url("pic2.jpg");
            public static readonly string title1_png = Url("title1.png");
        }
    
        public static readonly string wardrobe_gif = Url("wardrobe.gif");
        public static readonly string wardrobe_bottom_gif = Url("wardrobe_bottom.gif");
        public static readonly string wardrobe_left_gif = Url("wardrobe_left.gif");
        public static readonly string wardrobe_right_gif = Url("wardrobe_right.gif");
        public static readonly string wardrobe_top_gif = Url("wardrobe_top.gif");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class wedges {
            private const string URLPATH = "~/Images/wedges";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string icon_wedges_jpg = Url("icon_wedges.jpg");
        }
    
        public static readonly string wedges_gif = Url("wedges.gif");
        public static readonly string wedges_s2_gif = Url("wedges_s2.gif");
        public static readonly string whitebutton_dottedline_gif = Url("whitebutton_dottedline.gif");
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class Scripts {}
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class Styles {}
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591


