// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace BR.ToteToToe.Web.Controllers
{
    public partial class WishlistController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public WishlistController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected WishlistController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Remove()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Remove);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult MyWishlist()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MyWishlist);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddToCartNormal()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddToCartNormal);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddToCartCustomize()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddToCartCustomize);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public WishlistController Actions { get { return MVC.Wishlist; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Wishlist";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Wishlist";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Remove = "Remove";
            public readonly string MyWishlist = "MyWishlist";
            public readonly string AddToCartNormal = "AddToCartNormal";
            public readonly string AddToCartCustomize = "AddToCartCustomize";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Remove = "Remove";
            public const string MyWishlist = "MyWishlist";
            public const string AddToCartNormal = "AddToCartNormal";
            public const string AddToCartCustomize = "AddToCartCustomize";
        }


        static readonly ActionParamsClass_Remove s_params_Remove = new ActionParamsClass_Remove();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Remove RemoveParams { get { return s_params_Remove; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Remove
        {
            public readonly string wishlistItemID = "wishlistItemID";
        }
        static readonly ActionParamsClass_MyWishlist s_params_MyWishlist = new ActionParamsClass_MyWishlist();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MyWishlist MyWishlistParams { get { return s_params_MyWishlist; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MyWishlist
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_AddToCartNormal s_params_AddToCartNormal = new ActionParamsClass_AddToCartNormal();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddToCartNormal AddToCartNormalParams { get { return s_params_AddToCartNormal; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddToCartNormal
        {
            public readonly string modelSizeID = "modelSizeID";
            public readonly string sku = "sku";
        }
        static readonly ActionParamsClass_AddToCartCustomize s_params_AddToCartCustomize = new ActionParamsClass_AddToCartCustomize();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddToCartCustomize AddToCartCustomizeParams { get { return s_params_AddToCartCustomize; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddToCartCustomize
        {
            public readonly string size = "size";
            public readonly string sku = "sku";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _WishlistItemList = "_WishlistItemList";
                public readonly string Index = "Index";
                public readonly string MyWishlist = "MyWishlist";
            }
            public readonly string _WishlistItemList = "~/Views/Wishlist/_WishlistItemList.cshtml";
            public readonly string Index = "~/Views/Wishlist/Index.cshtml";
            public readonly string MyWishlist = "~/Views/Wishlist/MyWishlist.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_WishlistController : BR.ToteToToe.Web.Controllers.WishlistController
    {
        public T4MVC_WishlistController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void RemoveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int wishlistItemID);

        public override System.Web.Mvc.ActionResult Remove(int wishlistItemID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Remove);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "wishlistItemID", wishlistItemID);
            RemoveOverride(callInfo, wishlistItemID);
            return callInfo;
        }

        partial void MyWishlistOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult MyWishlist(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MyWishlist);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            MyWishlistOverride(callInfo, id);
            return callInfo;
        }

        partial void AddToCartNormalOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int modelSizeID, string sku);

        public override System.Web.Mvc.ActionResult AddToCartNormal(int modelSizeID, string sku)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddToCartNormal);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "modelSizeID", modelSizeID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sku", sku);
            AddToCartNormalOverride(callInfo, modelSizeID, sku);
            return callInfo;
        }

        partial void AddToCartCustomizeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string size, string sku);

        public override System.Web.Mvc.ActionResult AddToCartCustomize(string size, string sku)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddToCartCustomize);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "size", size);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sku", sku);
            AddToCartCustomizeOverride(callInfo, size, sku);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
