//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BR.ToteToToe.Web.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class lnkmodelsize
    {
        public lnkmodelsize()
        {
            this.lnkwishlists = new HashSet<lnkwishlist>();
            this.lnksalesorders = new HashSet<lnksalesorder>();
        }
    
        public int ID { get; set; }
        public int ModelID { get; set; }
        public int ColourDescID { get; set; }
        public string Size { get; set; }
        public int Quantity { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> UpdateDT { get; set; }
        public bool Active { get; set; }
    
        public virtual refcolourdesc refcolourdesc { get; set; }
        public virtual ICollection<lnkwishlist> lnkwishlists { get; set; }
        public virtual ICollection<lnksalesorder> lnksalesorders { get; set; }
        public virtual refmodel refmodel { get; set; }
    }
}
