//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BR.ToteToToe.Web.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class lnksoaddress
    {
        public int ID { get; set; }
        public int SalesOrderID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string CityTown { get; set; }
        public string State { get; set; }
        public string Postcode { get; set; }
        public bool IsBilling { get; set; }
        public bool IsShipping { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> UpdateDT { get; set; }
        public int ChooseAddress { get; set; }
    
        public virtual refcountry refcountry { get; set; }
        public virtual trnsalesorder trnsalesorder { get; set; }
    }
}
