//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BR.ToteToToe.Web.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class refcustomizemodel
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Style { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public string MainImage { get; set; }
        public string SubImage { get; set; }
        public decimal Price { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> UpdateDT { get; set; }
        public bool Active { get; set; }
    }
}
