//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BR.ToteToToe.Web.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class refmodel
    {
        public refmodel()
        {
            this.lnkcollectionmodels = new HashSet<lnkcollectionmodel>();
            this.lnkmodelcolourdescs = new HashSet<lnkmodelcolourdesc>();
            this.lnkmodelsizes = new HashSet<lnkmodelsize>();
            this.lnkmodellifestyles = new HashSet<lnkmodellifestyle>();
            this.lnkmodeltrends = new HashSet<lnkmodeltrend>();
        }
    
        public int ID { get; set; }
        public int BrandID { get; set; }
        public string Gender { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int HeelHeight { get; set; }
        public string MainImage { get; set; }
        public string SubImage { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> UpdateDT { get; set; }
        public bool Active { get; set; }
        public Nullable<decimal> DiscountPrice { get; set; }
    
        public virtual ICollection<lnkcollectionmodel> lnkcollectionmodels { get; set; }
        public virtual ICollection<lnkmodelcolourdesc> lnkmodelcolourdescs { get; set; }
        public virtual ICollection<lnkmodelsize> lnkmodelsizes { get; set; }
        public virtual refbrand refbrand { get; set; }
        public virtual ICollection<lnkmodellifestyle> lnkmodellifestyles { get; set; }
        public virtual ICollection<lnkmodeltrend> lnkmodeltrends { get; set; }
    }
}
