//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BR.ToteToToe.Web.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class trnsalesorder
    {
        public trnsalesorder()
        {
            this.lnksoaddresses = new HashSet<lnksoaddress>();
            this.lnksalesorders = new HashSet<lnksalesorder>();
        }
    
        public int ID { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public string Receipient { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string State { get; set; }
        public string Postcode { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DeliveryDT { get; set; }
        public decimal SubTotal { get; set; }
        public decimal GrandTotal { get; set; }
        public Nullable<int> VoucheID { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> UpdateDT { get; set; }
        public string PaymentGatewayTransID { get; set; }
    
        public virtual ICollection<lnksoaddress> lnksoaddresses { get; set; }
        public virtual refstatu refstatu { get; set; }
        public virtual tblvoucher tblvoucher { get; set; }
        public virtual ICollection<lnksalesorder> lnksalesorders { get; set; }
    }
}
