//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BR.ToteToToe.Web.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TTTEntities : DbContext
    {
        public TTTEntities()
            : base("name=TTTEntities")
        {
    		this.Configuration.LazyLoadingEnabled = true;
    		this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<lnkcollectionmodel> lnkcollectionmodels { get; set; }
        public DbSet<lnkcolourpriority> lnkcolourpriorities { get; set; }
        public DbSet<lnktrendpriority> lnktrendpriorities { get; set; }
        public DbSet<refbrand> refbrands { get; set; }
        public DbSet<refcategory> refcategories { get; set; }
        public DbSet<refcollection> refcollections { get; set; }
        public DbSet<refcolour> refcolours { get; set; }
        public DbSet<refcolourdesc> refcolourdescs { get; set; }
        public DbSet<reflifestyle> reflifestyles { get; set; }
        public DbSet<reftrend> reftrends { get; set; }
        public DbSet<tblvoucher> tblvouchers { get; set; }
        public DbSet<trnwishlist> trnwishlists { get; set; }
        public DbSet<lnkmodelsize> lnkmodelsizes { get; set; }
        public DbSet<lnkmodelimage> lnkmodelimages { get; set; }
        public DbSet<refstatu> refstatus { get; set; }
        public DbSet<refcountry> refcountries { get; set; }
        public DbSet<tblaccess> tblaccesses { get; set; }
        public DbSet<tbladdress> tbladdresses { get; set; }
        public DbSet<lnkwishlist> lnkwishlists { get; set; }
        public DbSet<lnkcustomizemodelimage> lnkcustomizemodelimages { get; set; }
        public DbSet<refcustomizemodel> refcustomizemodels { get; set; }
        public DbSet<lnksoaddress> lnksoaddresses { get; set; }
        public DbSet<tblrecentview> tblrecentviews { get; set; }
        public DbSet<trnsalesorder> trnsalesorders { get; set; }
        public DbSet<lnksalesorder> lnksalesorders { get; set; }
        public DbSet<logpayment> logpayments { get; set; }
        public DbSet<refmodel> refmodels { get; set; }
        public DbSet<lnkmodellifestyle> lnkmodellifestyles { get; set; }
        public DbSet<lnkmodeltrend> lnkmodeltrends { get; set; }
        public DbSet<lnkmodelcolourdesc> lnkmodelcolourdescs { get; set; }
    }
}
